resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/yk0407/flight-school.git
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/build.yml

